# These categories will be applied to all DAGs in the repo.
categories:
  - Data Quality
  - AI + Machine Learning
# List of DAGs that should be published to the Astronomer Registry.
dags:
  - path: dags/rose_classification.py