version: '3.1'
services:
  postgres_data:
    image: postgres:15.4-alpine
    volumes:
      - ${PWD}/include/postgres:/var/lib/postgresql/data
      - ${PWD}/include:/include
    networks:
      - airflow
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"  
  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway"  